#! /bin/bash

# A script to quickly create a branch, add a commit, and push it up.

set -eo pipefail

if [ -z "$1" ]; then
  echo ERROR: Must have at least a description
  exit 1
fi

current_branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$current_branch" != master ] && [ "$current_branch" != main ]; then
  echo WARNING: YOU BRANCHED OF OFF "$current_branch", not main or master.
fi

if [ -z "$2" ]; then
  # if there's no second argument, we only have a description
  description=$1
  kebab_name=$(echo "$description" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')
  commit_message="${description}"
  branch_name=$kebab_name
else
  # ticket and description behavior
  ticket_prefix=$1
  description=$2
  kebab_name=$(echo "$description" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')
  commit_message="${ticket_prefix} ${description}"
  branch_name="$ticket_prefix"-"$kebab_name"
fi

git checkout -b "$branch_name"
git add .
git commit -m "$commit_message"
git push -u origin "$branch_name"
